Revert: Load before BlueMap
It was making causing a crash:
> org.bukkit.plugin.InvalidPluginException: Exception initializing main class `com.technicjelle.bluemapofflineplayermarkers.BlueMapOfflinePlayerMarkers`
> Caused by: java.lang.NoClassDefFoundError: de/bluecolored/bluemap/api/BlueMapAPI